using System.Text;
using HomeScoutCopilot.API.Service;

namespace HomeScoutCopilot.AgentOps;

/// <summary>
/// Builds the declarative HomeScout agent manifest (GenAIOps "agent.yaml" pattern) from the
/// single-sourced agent definition — the versioned prompt asset (<see cref="AgentPrompt"/>)
/// and the tool set (<see cref="HomeScoutAgentTools.ToolNames"/>). This is the offline,
/// fully-testable half of the deploy step. The live registration of a versioned Foundry
/// agent (AgentAdministrationClient.CreateAgentVersion) is a separate, live-verified slice —
/// see wiki/__plans/03-backend/genaiops-tooling-plan.md.
/// </summary>
public static class AgentManifest
{
    /// <summary>The agent name — stable across versions.</summary>
    public const string AgentName = "HomeScout";

    /// <summary>
    /// Assemble the agent definition. <paramref name="modelDeploymentName"/> is the Foundry
    /// model deployment (environment-specific); everything else is sourced from the code.
    /// </summary>
    public static AgentDefinition Build(string modelDeploymentName) =>
        new(
            Name: AgentName,
            Model: modelDeploymentName,
            PromptVersion: AgentPrompt.Version,
            InstructionsFile: $"Prompts/homescout.{AgentPrompt.Version}.md",
            Instructions: AgentPrompt.Instructions,
            ToolNames: HomeScoutAgentTools.ToolNames);

    /// <summary>
    /// Serialise to the declarative agent manifest (name, model, instructions_file, tools).
    /// Fields are simple scalars/identifiers, so a small deterministic writer is used rather
    /// than pulling in a YAML dependency.
    /// </summary>
    public static string ToYaml(AgentDefinition definition)
    {
        var sb = new StringBuilder();
        sb.Append("# Generated by HomeScoutCopilot.AgentOps — declarative agent manifest (GenAIOps).\n");
        sb.Append("# Source of truth is the prompt asset; regenerate on prompt/model/tool changes.\n");
        sb.Append($"name: {definition.Name}\n");
        sb.Append($"model: {definition.Model}\n");
        sb.Append($"instructions_file: {definition.InstructionsFile}\n");
        sb.Append("tools:\n");
        foreach (var tool in definition.ToolNames)
        {
            sb.Append($"  - {tool}\n");
        }

        return sb.ToString();
    }
}
